"""empty message

Revision ID: 4f5e8d86702c
Revises: a6168c7ceb68
Create Date: 2024-02-26 21:09:18.802978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f5e8d86702c'
down_revision = 'a6168c7ceb68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('memo_body', sa.Text(), nullable=True))
        batch_op.drop_column('memos')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('memos', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('memo_body')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
